version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  target-branch: dev
  versioning-strategy: increase
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.893.0
    - 2.894.0
  - dependency-name: babel-preset-latest-node
    versions:
    - 5.5.0
  - dependency-name: promise-pool-ext
    versions:
    - 1.3.13
  - dependency-name: "@blackflux/robo-config-plugin"
    versions:
    - 4.1.1
    - 4.1.2
    - 4.1.3
  - dependency-name: chai
    versions:
    - 4.3.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.0.0
  - dependency-name: aws-sdk-wrap
    versions:
    - 7.2.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
